# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Musings of a Software Engineer
baseurl: "" 
url: "" 
permalink: /blog/:year/:month/:day/:title
navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about/
  - title: Blog
    url: /blog/
  - title: Resume
    url: /resume/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
